
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TRANWRD = 12;
  public static final int DERSYM = 9;
  public static final int RCUR = 8;
  public static final int LSQ = 5;
  public static final int COLON = 4;
  public static final int SNUM = 16;
  public static final int RSQ = 6;
  public static final int EOF = 0;
  public static final int SEP = 14;
  public static final int STATEWRD = 13;
  public static final int LALRWRD = 3;
  public static final int LCUR = 7;
  public static final int ID = 15;
  public static final int DOTSYM = 11;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int START = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "START",
  "LALRWRD",
  "COLON",
  "LSQ",
  "RSQ",
  "LCUR",
  "RCUR",
  "DERSYM",
  "COMMA",
  "DOTSYM",
  "TRANWRD",
  "STATEWRD",
  "SEP",
  "ID",
  "SNUM"
  };
}

